"use client";
import Link from "next/link";
import { properties, brand } from "@/lib/data";
import KPRCalculator from "@/components/KPRCalculator";
import WAButton from "@/components/WAButton";
import { useState } from "react";
export default function Home(){
  const [filter,setFilter]=useState("Semua");
  const filtered = filter==="Semua"?properties:properties.filter(p=>p.type.includes(filter)||p.location.includes(filter));
  return (<main className="min-h-screen bg-[#0F0F0E] text-[#F5F1EB]">
    <nav className="sticky top-0 z-50 bg-[#0F0F0E]/80 backdrop-blur border-b border-white/10"><div className="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center"><img src="/logos/kurasi_bali_white_cutout.png" alt="KURASI BALI" className="h-7" /><div className="hidden md:flex gap-6 text-[10px] uppercase tracking-widest opacity-60"><Link href="/">Terkurasi</Link><Link href="/takeover">Takeover</Link></div><WAButton message={`Halo Kurasi Bali, mau konsultasi properti terkurasi dari ${brand.domain}`} className="bg-[#FF4E11] text-black px-5 py-2.5 rounded-full text-xs font-bold uppercase">WA Kurator</WAButton></div></nav>
    <section className="max-w-7xl mx-auto px-6 py-16 md:py-24 grid md:grid-cols-2 gap-10"><div><div className="inline-flex text-[10px] tracking-[0.2em] border border-white/10 rounded-full px-4 py-1.5">● {brand.domain} — 150+ Ditolak, Hanya Yang Layak Tayang</div><h1 className="mt-6 text-6xl md:text-7xl font-black leading-[0.85] uppercase tracking-tighter">KAMI<br/>TIDAK<br/>JUAL<br/>SEMUA.<br/><span className="text-[#FF4E11] italic font-serif normal-case">Kami hanya<br/>kurasi yang<br/>layak.</span></h1><p className="mt-6 opacity-60 max-w-md leading-relaxed">{brand.manifesto} Legal tidak clear, harga ngarang, akses tidak layak — tidak lolos kurasi.</p><div className="mt-8 flex gap-2 flex-wrap">{["Semua","Freehold","Leasehold","Canggu"].map(f=><button key={f} onClick={()=>setFilter(f)} className={`px-4 py-2 rounded-full text-xs uppercase border ${filter===f?"bg-white text-black":"border-white/10 opacity-60"}`}>{f}</button>)}</div></div><div className="bg-[#1A1A19] rounded-[32px] p-6 border border-white/10"><div className="text-[#E1FF00] text-[10px] tracking-widest uppercase">Prinsip Kurasi: Legal Clear • Harga Jujur • Akses Layak</div><div className="mt-6 grid grid-cols-2 gap-4">{filtered.slice(0,4).map(p=><Link key={p.slug} href={`/properti/${p.slug}`} className="bg-[#1F1F1E] rounded-2xl p-4 border border-white/5 hover:border-[#FF4E11]/30"><div className="text-3xl">{p.image}</div><div className="mt-2 font-bold text-sm leading-tight">{p.title}</div><div className="text-xs opacity-50">{p.location}</div><div className="text-[#FF4E11] font-bold mt-1">Rp {p.priceText}</div><div className="text-[9px] mt-1 bg-white text-black inline-block px-2 py-0.5 rounded-full">LOLOS KURASI ✓</div></Link>)}</div></div></section>
    <section className="max-w-7xl mx-auto px-6"><div className="flex justify-between items-end"><h2 className="text-3xl font-black uppercase tracking-tighter">TERKURASI<br/>MINGGU INI / BALI</h2><div className="text-[10px] opacity-40 uppercase">Hanya yang layak</div></div><div className="grid md:grid-cols-3 gap-6 mt-8">{filtered.map(p=><Link key={p.slug} href={`/properti/${p.slug}`} className="group bg-[#1F1F1E] rounded-[24px] overflow-hidden border border-white/5"><div className="h-56 bg-gradient-to-br from-[#1A1A19] to-[#0F0F0E] flex items-center justify-center text-6xl">{p.image}</div><div className="p-5"><div className="flex justify-between text-[10px] uppercase"><span className="bg-white text-black px-2 py-1 rounded-full">{p.type}</span><span className="opacity-40">{p.location}</span></div><div className="mt-4 font-bold leading-tight">{p.title}</div><div className="mt-1 text-sm opacity-50">{p.lt} • {p.cert}</div><div className="mt-3 flex justify-between"><span className="text-xl font-black text-[#FF4E11]">Rp {p.priceText}</span><span className="text-xs opacity-60 group-hover:opacity-100">Lihat →</span></div></div></Link>)}</div></section>
    <section className="max-w-7xl mx-auto px-6 py-20"><KPRCalculator /></section>
    <footer className="border-t border-white/10 py-16 text-center"><img src="/logos/kurasi_bali_lockup_cutout.png" alt="KURASI BALI Bali Property Curated" className="h-20 mx-auto invert" /><div className="text-2xl font-black tracking-tighter mt-6">www.kurasibali.com</div><div className="text-xs opacity-40 mt-2">WA 085156282660 • IG @kurasibali • @adimoyo_ • @takeoverkreditbali • Badung, Bali • Bukan Makelar. Kami Kurator.</div></footer>
  </main>)
}
