
export type Property = { slug: string; title: string; location: string; price: number; priceText: string; type: string; lt: string; lb: string; kt: number; km: number; cert: string; desc: string; image: string; }
export const properties: Property[] = [
  { slug: "villa-2br-canggu-berawa", title: "Villa 2BR Modern Berawa", location: "Berawa, Canggu", price: 3800000000, priceText: "3.8M", type: "Leasehold 25th", lt: "200m2", lb: "150m2", kt: 2, km: 2, cert: "Leasehold", desc: "Lolos Kurasi: Jalan 6m, 5 menit ke Finns Beach, ROI tinggi, legal clear, akses mobil.", image: "🏝️" },
  { slug: "tanah-500m2-uluwatu-bingin", title: "Tanah 500m2 View Laut Bingin", location: "Bingin, Uluwatu", price: 1200000000, priceText: "1.2M", type: "Freehold", lt: "500m2", lb: "-", kt: 0, km: 0, cert: "SHM", desc: "Lolos Kurasi: View laut abadi, jalan 5m, ITR kuning, siap bangun.", image: "🌊" },
  { slug: "villa-3br-ubud-jungle", title: "Villa 3BR Jungle Ubud", location: "Ubud", price: 5500000000, priceText: "5.5M", type: "Leasehold 30th", lt: "600m2", lb: "250m2", kt: 3, km: 3, cert: "Leasehold", desc: "Lolos Kurasi: Private jungle, sungai di belakang, super private.", image: "🌿" },
  { slug: "tanah-1000m2-tabanan-sawah", title: "Tanah 1000m2 View Sawah Tabanan", location: "Tabanan", price: 900000000, priceText: "900jt", type: "Freehold", lt: "1000m2", lb: "-", kt: 0, km: 0, cert: "SHM", desc: "Lolos Kurasi: Sawah terasering abadi, cocok villa keluarga.", image: "🌾" },
  { slug: "villa-1br-modern-sanur", title: "Villa 1BR Modern Sanur", location: "Sanur", price: 2100000000, priceText: "2.1M", type: "Freehold", lt: "150m2", lb: "90m2", kt: 1, km: 1, cert: "SHM", desc: "Lolos Kurasi: Dekat pantai Sanur, ready stock, desain minimalis.", image: "☀️" },
  { slug: "commercial-canggu-batu-bolong", title: "Commercial Batu Bolong", location: "Batu Bolong, Canggu", price: 4200000000, priceText: "4.2M", type: "Leasehold 20th", lt: "300m2", lb: "200m2", kt: 0, km: 2, cert: "Leasehold", desc: "Lolos Kurasi: Traffic tinggi, cocok cafe & boutique.", image: "🏢" },
];
export const brand = { name: "KURASI BALI", domain: "kurasibali.com", tagline: "Bali Property, Curated.", wa: "085156282660", waNumber: "6285156282660", ig: "@kurasibali", manifesto: "Kami tidak jual semua. Kami hanya kurasi yang layak. 70% listing kami tolak." };
