export const listings = [
  {
    id: "griya-elok-ayani",
    title: "Rumah Siap Huni A.Yani Utara",
    location: "Jl. Suradipa II, Gg. Uma Dewi – A.Yani Utara, Denpasar",
    area: "LT 100m² / LB 65m²",
    bedrooms: "3 Kamar Tidur",
    bathrooms: "1 Kamar Mandi",
    facing: "Hadap Utara",
    access: "Akses Jalan 4,5 Meter",
    listrik: "1.300 Watt",
    air: "Air Sumur",
    features: ["Ruang Keluarga", "Dapur", "Carport", "1 Lantai"],
    price: "Rp 985 Juta",
    priceNote: "Belum termasuk BPHTB & BBN",
    status: "HANYA 1 UNIT",
    image: "/griyaelok-1.webp",
    image2: "/griyaelok-2.webp",
    tags: ["SHM", "Siap Huni", "Denpasar"],
    discount: "Siap Huni",
    description: "Rumah 1 lantai dengan luas tanah 100 m² di kawasan Denpasar Utara. Cocok untuk keluarga kecil maupun investasi",
  },
  {
    id: "villa-bomba",
    title: "Villa Bomba Umalas",
    location: "Umalas, Badung",
    area: "LT 250m² / 2BR",
    price: "Rp 2.8 M",
    image: "/villa-bomba.webp",
    tags: ["SHM", "PBG"],
    discount: "-32% bawah pasar",
  },
  {
    id: "villa-ubud",
    title: "Villa Ubud Jungle View",
    location: "Tegallalang, Ubud",
    area: "LT 480m² / 3BR",
    price: "Rp 1.9 M",
    image: "/villa-ubud.webp",
    tags: ["SHM"],
    discount: "-28%",
  },
  {
    id: "tanah-bingin",
    title: "Tanah Bingin Cliff Front",
    location: "Bingin, Uluwatu",
    area: "LT 600m²",
    price: "Rp 3.2 M",
    image: "/tanah-bingin.webp",
    tags: ["SHM"],
    discount: "-41%",
  },
];

export const waLink = "https://wa.me/6285156282660?text=Halo%20Kurasi%20Bali%20%F0%9F%91%8B%20Saya%20mau%20info%20Rumah%20Siap%20Huni%20A.Yani%20Utara%20Rp%20985jt%20-%20Jl.%20Suradipa%20II";
