export const listings = [
  {
    id: "griya-elok",
    title: "Griya Elok Jimbaran",
    location: "Jimbaran, Badung",
    area: "90m² / 2BR",
    remaining: "Sisa 10 tahun",
    installment: "Rp 12jt/bln",
    takeoverPrice: "Rp 850 Jt",
    image: "/griyaelok-1.webp",
    image2: "/griyaelok-2.webp",
    tags: ["SHM", "IMB", "Ready"],
    discount: "-25% bawah pasar",
  },
  {
    id: "villa-bomba",
    title: "Villa Bomba Umalas",
    location: "Umalas, Badung",
    area: "250m² / 2BR",
    remaining: "Sisa 12 tahun",
    installment: "Rp 28jt/bln",
    takeoverPrice: "Rp 2.8 M",
    image: "/villa-bomba.webp",
    tags: ["SHM", "PBG", "SLO"],
    discount: "-32% bawah pasar",
  },
  {
    id: "villa-ubud",
    title: "Villa Ubud Jungle View",
    location: "Tegallalang, Ubud",
    area: "480m² / 3BR",
    remaining: "Sisa 9 tahun",
    installment: "Rp 18jt/bln",
    takeoverPrice: "Rp 1.9 M",
    image: "/villa-ubud.webp",
    tags: ["SHM", "PBG"],
    discount: "-28% bawah pasar",
  },
  {
    id: "tanah-bingin",
    title: "Tanah Bingin Cliff Front",
    location: "Bingin, Uluwatu",
    area: "600m²",
    remaining: "Sisa 15 tahun",
    installment: "Rp 22jt/bln",
    takeoverPrice: "Rp 3.2 M",
    image: "/tanah-bingin.webp",
    tags: ["SHM", "Pondok Wisata"],
    discount: "-41% bawah pasar",
  },
];

export const waLink = "https://wa.me/6285156282660?text=Halo%20Kurasi%20Bali%20%F0%9F%91%8B%20Saya%20mau%20konsultasi%20Griya%20Elok%20Jimbaran%20yang%20takeover%20kredit";
